### PR TITLE
Put footer to fixed position and added alt and title tags to images

### LINKED ISSUE #123: add alt tags to images

### PR DESCRIPTION
**Pull request by compassface**
fixes #123 - josh

### CODE REVIEW

File: public/js/checkout.js [hunk 1]
```diff
@@ -324,5 +324,8 @@ $(document).ready(function() {
         centerDiv.appendChild(h1Thing);
 
         $('.content').append(centerDiv);
-    }
+    };
+
+
+
```
Comment (joshuarichard) [inline public/js/checkout.js]: delete 328, 329, and 330

File: public/js/children.js [hunk 2]
```diff
@@ -2,6 +2,8 @@
 /* eslint no-undef: 0 */
 
 $(document).ready(function() {
+
+
```
Comment (joshuarichard) [inline public/js/children.js]: delete 5 and 6

**Comment by joshuarichard** [comment]
found lint :(

File: public/js/children.js [hunk 3]
```diff
@@ -125,6 +127,8 @@ $(document).ready(function() {
         img.id = 'child-picture';
         img.className = 'img-responsive center-block child-picture';
         img.src = 'data:image/image;base64,' + picture;
+        img.alt = "Picture of Child";
+        img.title = "Picture of Child";
```
Comment (joshuarichard) [inline public/js/children.js]: also lines 130 and 131 should use `'` instead of `"` (single quotes instead of double quotes)

**Comment by joshuarichard** [comment]
@compassface even after you make those changes I commented eslint will fail because of a couple of other files.... don't worry about those i've already fixed the issues in my other two pull requests

**Comment by joshuarichard** [comment]
found lint :(

**Comment by joshuarichard** [comment]
found lint :(
